// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgucbrsdilgukyqnwryl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndWNicnNkaWxndWt5cW53cnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODg1MDYsImV4cCI6MjA3MjU2NDUwNn0._ywpK3vCM6BiLHlXJIlllY3udoIm95jOb5d_YXuVMhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});